In [1]:
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [3]:
print(a[0],a[1],a[2])
a[0]=5
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

1 2 3
[5 2 3]
(2, 3)
1 2 4


In [4]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [5]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [7]:
c=np.full((5,5),8)
print(c)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [8]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [9]:
e=np.random.random((2,2))
print(e)

[[0.53464595 0.28169433]
 [0.1553797  0.39054925]]


In [10]:
import numpy as np
np.linspace(2.0, 3.0, num=5)
np.linspace(2.0, 3.0, num=5, endpoint=False)
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [13]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2, 1:3]
print(a[0,1])
print(b)

2
[[2 3]
 [6 7]]


In [14]:
b[0,0]=77
print(b)

[[77  3]
 [ 6  7]]


In [17]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [19]:
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [20]:
x=np.array([1,2])
print(x.dtype)
x=np.array([1.0,2.0])
print(x.dtype)
x=np.array([1,2],dtype=np.int64)
print(x.dtype)

int32
float64
int64


In [21]:
z=np.array([[1,2],[3,4]],dtype=np.int64)
y=np.array([[5,6],[7,8]],dtype=np.int64)
print(np.multiply(y,z))

[[ 5 12]
 [21 32]]


In [22]:
z=np.array([[1,2],[3,4]],dtype=np.int64)
y=np.array([[5,6],[7,8]],dtype=np.int64)
print(np.divide(y,z))

[[5.         3.        ]
 [2.33333333 2.        ]]


In [23]:
z=np.array([[1,2],[3,4]],dtype=np.int64)
y=np.array([[5,6],[7,8]],dtype=np.int64)
print(np.subtract(y,z))

[[4 4]
 [4 4]]


In [24]:
z=np.array([[1,2],[3,4]],dtype=np.int64)
y=np.array([[5,6],[7,8]],dtype=np.int64)
print(np.sqrt(y))

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [26]:
v=np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


In [27]:
arr=np.array([[1,2],
              [3,4]])
print("Original Array:",arr)
w,v=np.linalg.eig(arr)
print("Eigen values of the array:",w)
print("Eigen vectors of the array:",v)

Original Array: [[1 2]
 [3 4]]
Eigen values of the array: [-0.37228132  5.37228132]
Eigen vectors of the array: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
